Added swap_tokens_fixed_input doc
elrondex/elrondex pull request #23
Opened 2022-02-18 01:33 UTC by victorflx

Not sure how an example for this function would look like.

2022-02-18 09:18 UTC, fabianflx commented on lib/elrondex/sc/pair_sc.ex
> +  Swaps token1 amount for a minimum of token2 amount.
Swaps a certain token amount for a minimum of another token amount.

I think it would be better like this.

2022-02-18 09:18 UTC, fabianflx commented on lib/elrondex/sc/pair_sc.ex
> +    * `account` - An elrond account (as described in lib/account)
There might be a better explication for what 'account' does eg: "the account that does the pair"

Also, I don't find the usage of the ()

2022-02-18 09:18 UTC, fabianflx commented on lib/elrondex/sc/pair_sc.ex
> +    * `value_in` - Token_in amount to be swapped
I think you can find a better format not just write 'token_in' eg: "First token"

2022-02-18 12:57 UTC, elrondex reviewed
general doc feedback

2022-02-18 12:57 UTC, elrondex commented on lib/elrondex/sc/pair_sc.ex
> +    * `pair` -  An elrond pair (as described in lib/pair)
Pair struct where we make token swap.

2022-02-18 12:57 UTC, elrondex commented on lib/elrondex/sc/pair_sc.ex
> +  Swaps a certain token amount for a minimum of another token amount.
Swaps a certain token amount with fix amount value on input and minimum value amount on output.

2022-02-18 12:57 UTC, elrondex commented on lib/elrondex/sc/pair_sc.ex
> +    * `token_in` - First token to be swapped
Input token identifier that we provide on input for swap operation.

2022-02-18 12:57 UTC, elrondex commented on lib/elrondex/sc/pair_sc.ex
> +    * `value_in` - Fixed amount of first token to be swapped
Fix value amount for input token. 
This value ammount will be transferred on Pair SC in order to perform swap.

2022-02-18 12:57 UTC, elrondex commented on lib/elrondex/sc/pair_sc.ex
> +    * `token_out` - Second token to be swapped
Output token identifier that swap operation will return in account.

2022-02-18 12:57 UTC, elrondex commented on lib/elrondex/sc/pair_sc.ex
> +    * `value_out` - Minimum amount of second token that we receive after swapping
Minimum amount for output token that require for an successful swap operation.

2022-02-21 17:42 UTC, elrondex requested changes

2022-02-21 17:42 UTC, elrondex commented on lib/elrondex/sc/pair_sc.ex
> +      iex> Elrondex.Test.Bob.swap_1_egld_to_min_100usdc
insert full call here with `Elrondex.Test.Bob.account()` and `Elrondex.Test.Pair.wegld_usdc_pair()`

2022-02-21 17:42 UTC, elrondex commented on lib/elrondex/sc/pair_sc.ex
> +        value_out_min
don't change here, this fixed_output swap

2022-02-21 17:42 UTC, elrondex commented on lib/elrondex/test/bob.ex
> +    def swap_1_egld_to_min_100usdc do
remove this

2022-02-21 17:42 UTC, elrondex commented on lib/elrondex/test/utils.ex
> +  defmodule Elrondex.Test.Utils do
Utils is too generic, let's have Pair here `Elrondex.Test.Pair`

2022-02-22 12:59 UTC, elrondex requested changes

2022-02-22 12:59 UTC, elrondex commented on lib/elrondex/test/pair.ex
> +    @network Network.get(:mainnet)
delete @network

2022-02-22 12:59 UTC, elrondex commented on lib/elrondex/test/pair.ex
> +    def wegld_usdc_pair_live do
delete wegld_usdc_pair_live

2022-02-22 20:40 UTC, closed without merging