Added GetFeeState
elrondex/elrondex pull request #27
Opened 2022-02-21 19:49 UTC by victorflx

2022-02-22 08:48 UTC, khumeia reviewed
Ar fi bine sa avem si un test pentru functie sa verificam ca face ce ar trebui.
De asemenea, hai sa adaugam si documentatie.

2022-02-23 12:35 UTC, elrondex requested changes

2022-02-23 12:35 UTC, elrondex commented on lib/elrondex/sc/pair_sc.ex
> +    |> REST.post_vm_values_string(network) do
REST.post_vm_values_int

2022-02-23 12:35 UTC, elrondex commented on lib/elrondex/sc/pair_sc.ex
> +        <<0>> -> {:ok, false}
0 -> {:ok, false}
1 -> {:ok, true}

2022-03-01 12:35 UTC, elrondex approved these changes

2022-03-01 12:36 UTC, merged